version: '3.7'


volumes:
  db_data:
    driver: "local"
  redis:
  redis-config:

services:

  backend:
    container_name: backend
    hostname: backend
    image: backend
    build:
      context: backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgresql
      - redis

  postgresql:
    container_name: postgresql
    hostname: postgresql
    image: postgresql
    build:
      context: postgresql/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: app
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/root/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=redis1234
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

